### ISSUE TITLE
simplify structure of releases

### ISSUE THREAD

**Issue by VladimirAlexiev** [SEMICeu/Core-Location-Vocabulary#1]
https://joinup.ec.europa.eu/solution/core-location-vocabulary/releases
and https://joinup.ec.europa.eu/release/core-location-vocabulary/100
show 9 zips for 1.00
- should be able to download all info at once (one consolidated zip)
- also should be able to access conceptual/descriptive info on the web, without having to download and open zips, eg:
  - Core_Vocabularies-Business_Location_Person_v1.00_Conceptual_Model_0.zip: Core_Vocabularies-Business_Location_Person_v1.00_Conceptual_Model.png
  - https://joinup.ec.europa.eu/site/core_location/rdfs.html does not show as webpage but as raw html??

**Comment by makxdekkers** [comment]
Vladimir: 

Thanks for the useful feedback.

We'll look at publishing consolidated ZIP file so you don't have to click several times for individual downloads.

The behaviour of https://joinup.ec.europa.eu/site/core_location/rdfs.html is clearly wrong. This will be repaired.

**Comment by EmidioStani** [comment]
To be considered for the future, it can be closed

**Comment by VladimirAlexiev** [comment]
Now https://joinup.ec.europa.eu/site/core_location/rdfs.html is broken.

I wonder why you closed this issue.
