### ISSUE TITLE
AdminUnit1 and AdminUnit2

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Location-Vocabulary#10]
In the definition you say that AdminUnit1 is country/region/state. I am not sure if AdminUnit2 is a country again. Isn't it modelled with the AdminUnit1? 

Why AdminUnit1 has a Code as type while AdminUnit2 has text? If it is recommended to use NUTS for AdminUnit2 its type should be a Code, right?

In the table of the definitions for AdminUnit1 the type is missing.

**Comment by SebastianSK** [comment]
+1

**Comment by dimi-schepers** [comment]
The data type for AdminUnitL1 (Code, i.e. skos:Concept) was added to the specification, [see here](https://semiceu.github.io/Core-Location-Vocabulary/releases/2.00/#Address%3Aadministrative%20unit%20level%201%20(country)).

**Comment by giorgialodi** [comment]
> There was a typo in the label of AdminUnitL2. It should be "coun**ty**/region/state", and not "count**r**y". This was fixed accordingly in the spec, [see here](https://semiceu.github.io/Core-Location-Vocabulary/releases/2.00/#Address%3Aadministrative%20unit%20level%202%20(county%2Fregion%2Fstate)).

I think that AdminLevel2 cannot be a text but rather a skos:Concept pointing  to a controlled vocabulary (recommended NUTS). See also #12

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, an agreement was reached to use Code as datatype for all the AdminUnitLevels. We propose to continue the discussion on the various levels and which codelist to use per level in issue #12.
