### ISSUE TITLE
Inconsistency between data types in XSD (text type) and specification (code)

### ISSUE THREAD

**Issue by SebastianSK** [SEMICeu/Core-Location-Vocabulary#11]
The specification says that the CoreLocation.Address.AdminUnitL1 is a Code and that a valid URI from the Publications Office Gender codelist has to be used.
The XSD file in V1.0 (did not find yet the xsds for 2.2) uses a data type "text" for AdminUnitL1. (same seems true for Core Person Gender  https://github.com/SEMICeu/Core-Person-Vocabulary/issues/18 ).

![image](https://user-images.githubusercontent.com/3493618/115833118-f95eb700-a413-11eb-86f6-cad42e0ae564.png)

![image](https://user-images.githubusercontent.com/3493618/115833270-214e1a80-a414-11eb-8fb1-87135beb2041.png)

The recommendation is to use the data type xs:anyURI or an own data type for codelists but not text.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, an agreement was reached to use Code as datatype for all the AdminUnitLevels. We propose to continue the discussion on the various levels and which codelist to use per level in issue #12. The XSD's will be updated accordingly once the release if finalised.
