### ISSUE TITLE
Administrative Unit: need for clarification

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Location-Vocabulary#17]
During the Core Vocs webinar dd. 2021-05-20, there was some misunderstanding on what exactly is understood with an Administrative Unit and what it covers. It was unclear whether administrative units refer to addresses and locations that should be seen as separate from jurisdictional rights, not withholding the fact that there could be a relationship between the two.

**Comment by laers** [comment]
I agree - there is a need for clarification. I would expect that Administrative Units is a way of descriping a Location, for instance Municipality XX has a name, identifier, geographical extend (borders) etc.
What about cadastral parcels and buildings? Has these kinds of locations types (?) being discussed as well?

**Comment by PeterParslow** [comment]
Is the existing European Commission INSPIRE concept useful? https://inspire.ec.europa.eu/featureconcept/AdministrativeUnit

**Comment by EmidioStani** [comment]
In the last release of Core Vocabularies, the AdminUnit class has been added to define hierarchical ways, in more structured format than AdminUnitL1 and AdminUnitL2: https://semiceu.github.io/Core-Location-Vocabulary/releases/2.00/
