### ISSUE TITLE
Registered address

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Location-Vocabulary#18]
During the Core Vocs webinar dd. 2021-04-23, a suggestion was made to include the registered address property within the Core Location Vocabulary, as it is currently used by both the Core Person Vocabulary and the Core Business Vocabulary.

Not that also within the Core Public Organisation Vocabulary, the address property is used.

**Comment by EmidioStani** [comment]
During the webinar of 02/12/2021, it was agreed to create the relation domicile between Person and Address.

**Comment by EmidioStani** [comment]
The new relation has been added in the consolidated diagram: https://github.com/SEMICeu/Core-Location-Vocabulary/tree/master/releases/2.00
