### ISSUE TITLE
Property adminUnitL2

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Location-Vocabulary#21]
The current range of the property is Text meaning that it is a datatype property, with the name of the region/county/state. However, in the usage note there is a recommendation of using some controlled vocabularies, making the range of that property Code (object property, no longer a data type property).

I think this point should be better specified. If the ideal world is to use a controlled vocabulary, the range of that property should be revised in Code.

Finally, since you recommend the use of NUTS, among others, if I want to use level 3 of NUTS, which property of the class Address should I use? The adminUnitL2 seems the latest level foreseen for expressing the territorial hierarchy, at least looking at the names of the property (well, yep there is postName which is the city that is another layer of the hierarchy). Can I use NUT3 anyway? Should I use adminUnitL2 for NUT3 (it seems to me not appropriate from a semantic perspective)?

**Comment by EmidioStani** [comment]
The range AdminUnitL1 and AdminUnitL2 has been changed to Text

A new class "AdminUnit" has been added to specify different levels, see: https://semiceu.github.io/Core-Location-Vocabulary/releases/2.00/#overview
