### ISSUE TITLE
Attribute for street name and number

### ISSUE THREAD

**Issue by andreea-pasare** [SEMICeu/Core-Location-Vocabulary#22]
In the XML notices for the standard forms there is an address field that contains street name plus street number (see example below):
![image](https://user-images.githubusercontent.com/88081600/178702188-7c175248-92df-4d40-acc4-cb26faa8d826.png)

The definition for locn:thoroughfare does not propose a number, only the street name. The definition for locn:fullAddress propose a complete address (including zip code, city name, etc.) written as a string.

How do you recommend to this use case?

**Comment by EmidioStani** [comment]
Hello @andreea-pasare ,

as you correctly say the "thoroughfare" includes of the street name while the "locator designator" includes the street number, so it is possible to use the combination of both.

**Comment by williamverbeeck** [comment]
During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed that eProcurement will look at the locator designator to correct and comply.
