### ISSUE TITLE
Expected Range "String" in the class Address should be replaced by "Literal"

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/Core-Location-Vocabulary#24]
"String" (xsd:string) is now in (and only in) the class Address (locn:Address) used as range for the properties which have "text without lang-tag". 

According to [Core Location Vocabulary](https://www.w3.org/ns/locn), except for locn:locatorId where no range specified, the other properties should have rdfs:Literal as range. 

[Disclaimer: I haven't checked thoroughly, so I may be wrong about some of them]

**Comment by EmidioStani** [comment]
"During the webinar on the review of Core Vocabularies on the 27th of October, it was agreed to: 
- Change expected range 'xsd:String' to 'rdfs:Literal' in Address:addressID, LocatorDesignator, poBox and postCode.
- Investigate an identifier class which could contain: identifier string/literal, identifier type and issuer of identifier.
- Add clarifying designer note.

The clarification note will be added in the usage note saying that "the datatype of the property is indicated as Literal ( keeping backward compatibility with the old W3C specification) that can be typed differently, see <a href="https://www.w3.org/TR/rdf11-concepts/#section-Graph-Literal">more</a>"
