### ISSUE TITLE
Location of RDFS definition of m8g:* properties and classes?

### ISSUE THREAD

**Issue by jakubklimek** [SEMICeu/Core-Location-Vocabulary#28]
@EmidioStani where is the RDFS definition of m8g:* properties and classes located? I [can't find it](https://github.com/search?q=org%3ASEMICeu+m8g%3AregisteredAddress&type=code) in the SEMICeu GitHub organization and the IRI, e.g. `http://data.europa.eu/m8g/registeredAddress` dereferences only to the generic Joinup page.

_Originally posted by @jakubklimek in https://github.com/SEMICeu/Core-Location-Vocabulary/issues/26#issuecomment-1350652528_

**Comment by EmidioStani** [comment]
Hello @jakubklimek ,

the persistent URI service is divided in 2 components:
1) the proxy, for dereferencing HTML responses e.g http://data.europa.eu/m8g/registeredAddress should redirect to https://semiceu.github.io/Core-Location-Vocabulary/releases/2.0.1/#Resource%3Aregistered%20address 

2) the puri, to satisfy RDF requests, currently with Accept header with text/turtle, application/n-triples and application/rdf+xml; we still need to evaluate what we want to keep. 

So I restarted the proxy service and it should work now. 

Is there a serialization you prefer/need ? Just to take it in account for our evaluation.

**Comment by jakubklimek** [comment]
@EmidioStani thanks. I prefer text/turtle and application/ld+json

**Comment by jakubklimek** [comment]
@EmidioStani ok, now I indeed get:
```turtle
$ curl -L -H"Accept: text/turtle" http://data.europa.eu/m8g/registeredAddress
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

<http://data.europa.eu/m8g/registeredAddress> a rdf:Property,
        owl:ObjectProperty ;
    rdfs:label "registered address"@en ;
    rdfs:comment "The registered address relationship links a Resource with the legally registered Address."@en ;
    rdfs:isDefinedBy <http://data.europa.eu/m8g> .
```

But, the original question was more about whether there is an RDFS file somewhere with all the m8g:* definitions, similarly to other core vocabularies. I am a bit confused because if the HTML version redirects to the Core Location Vocabulary, then I would assume that `m8g:registeredAddress` is considered a part of that. But it is not defined in its [RDFS file](https://github.com/SEMICeu/Core-Location-Vocabulary/blob/master/releases/2.00/voc/core-location-ap.ttl).

**Comment by bertvannuffelen** [comment]
@jakubklimek 

This is a partly due to historical reasons. Instead of creating within the m8g a subnamespace that would coincide with each Core Vocabulary all terms have been placed in the same namespace (the root). 

That creates a mismatch between the scope: from the html representation this is a subset, but from the RDF representation this is like a random split. 
We have created the Consolidated Diagram that covers all terms and associated with that the complete RDF could be associated, but that has not yet found an "official publication" place in its own right.

But normally you should be able to curl -H "Accept:text/turtle" http://data.europa.eu/m8g to get the full RDF.

**Comment by jakubklimek** [comment]
@bertvannuffelen I understand, but the dereference service must take the data from somewhere, right? Could the contents of that "somewhere" be published as a full RDF file, maybe temporarily, in a separate repo or something like that? It is nice that the individual m8g terms are dereferencable, but I want to see/use all m8g terms that are defined, e.g. in a modeling tool that would allow me to actually work with the terms. 

Actually, the only place I found a set of m8g definitions, more specifically the definition of `m8g:registeredAddress` is [here](https://github.com/SEMICeu/uri.semic.eu-puris/tree/2b40400703e9651ba4450e65a29c45a9f91575ab/releases/m8g) so I guess one could download the whole directory to get the definitions, if that is the source.

> But normally you should be able to curl -H "Accept:text/turtle" http://data.europa.eu/m8g to get the full RDF.

Unfortunately, `$ curl -L -H "Accept:text/turtle" http://data.europa.eu/m8g` yields the HTML page.

**Comment by jakubklimek** [comment]
Maybe there could be a GitHub Action defined on the repo that just collects the triples from the individual `.ttl` files and stores it in a single file for convenience?

**Comment by bertvannuffelen** [comment]
> Actually, the only place I found a set of m8g definitions, more specifically the definition of `m8g:registeredAddress` is [here](https://github.com/SEMICeu/uri.semic.eu-puris/tree/main/releases/m8g) so I guess one could download the whole directory to get the definitions, if that is the source.
> 
yes, that is the data layer for the puri proxy service. The goal is that contains the full m8g namespace. 

> > But normally you should be able to curl -H "Accept:text/turtle" http://data.europa.eu/m8g to get the full RDF.
> 
> Unfortunately, `$ curl -L -H "Accept:text/turtle" http://data.europa.eu/m8g` yields the HTML page.

That is a bug then. I will fix it.

**Comment by EmidioStani** [comment]
I have an experimental python script that takes all SHACL shapes files
stored in a folder that and creates one rdf file to and for each subject of
triples generates the rdf descriptions (turtle, rdf/XML, n-triples) you get
in the dereference.

Maybe we should integrate it in the publication process

**Comment by jgmikael** [comment]
Hi, I was referred from my initial issue #43 (closed) to this issue. 
Can you please explain to a layman whether it's possible to publish the JSON-LD version of the Core Vocabularies in the same way as the RDF you are discussing above? 

In our interoperability tool it's possible to for instance point directly to https://vocabulary.uncefact.org/ and then make use of the vocabulary when modeling SHACL Shapes based on the original "reference data model". 

If I point to http://data.europa.eu/m8g at the moment nothing happens :-)

**Comment by jakubklimek** [comment]
@jgmikael Just out of curiosity, can you provide details on you interoperability tool?

> That is a bug then. I will fix it.

@bertvannuffelen any progress on fixing the bug?

**Comment by jgmikael** [comment]
@jakubklimek 
General info about the "Interoperability Platform" that consists of several tools: https://wiki.dvv.fi/display/YTIJD/Finnish+interoperability+platform+and+tools

On this particular page you can find a technical overview of the platform architecture: https://wiki.dvv.fi/display/YTIJD/Material+in+English

**Comment by jgmikael** [comment]
Hi, since my initial issues opened in both the Person and Business pages were closed with a reference to this discussion it would be nice to know whether anyone is actually doing anything with my requests? Please respond also if you find it totally irrelevant, which I simply don't know why anyone would.

**Comment by EmidioStani** [comment]
The properties under m8g namespace can now be reached via content negotiation as JSON-LD, example:

http://data.europa.eu/m8g/accessibility 

with Accept header set to application/ld+json

To get overall, redirection has to be put in place.

**Comment by jakubklimek** [comment]
@EmidioStani @bertvannuffelen any idea when this will be made functional? It has been more than 2 months since I opened the issue...

**Comment by EmidioStani** [comment]
There is in place a way to generate and redirect m8g terms under:

http://data.europa.eu/m8g/
