### ISSUE TITLE
Typo in diagram class locn:Address - use namespace locn for postCode

### ISSUE THREAD

**Issue by init-dcat-ap-de** [SEMICeu/Core-Location-Vocabulary#3]
The diagram under https://www.w3.org/ns/locn shows lcon:postCode  instead of locn:postCode

![image](https://user-images.githubusercontent.com/14979304/47643717-92c2f000-db6c-11e8-8a17-9e245397986f.png)

**Comment by EmidioStani** [comment]
This can be considered closed as @andrea-perego replied
