### ISSUE TITLE
Range of locn:geometry

### ISSUE THREAD

**Issue by dimi-schepers** [SEMICeu/Core-Location-Vocabulary#5]
In [the specification](https://www.w3.org/ns/locn#locn:geometry), the range of the property `locn:geometry` is set to the class `locn:Geometry`. Nevertheless, in the usage note, it is mentioned that literals and URIs are also accepted ranges (see also the examples). We therefore propose to make the range a `owl:unionOf` of those three.

**Comment by dimi-schepers** [comment]
During the Core Vocs webinar dd. 2021-05-20, the above proposition was challenged. It was mentioned that everything was already included in the Geometry class. If there is a need to use Geonames URI, the URI property in Location should be used. Therefore, the proposed resolution to this issue would be that the geometry property should always point to an instance of the Geometry class (and not to literals nor URI’s).

**Comment by PeterParslow** [comment]
The example of using a Geonames URI suggests some confusion. A Geonames URI points to a named place, not a geometry. The data item in Geonames (representing e.g. a town) contains/describes "more than" the geometry*, but also only provides very little "geometry" - just a WGS84 latitude/longitude point.

*for example, alternative names, post codes, administrative hierarchy, population

A Geonames URI is a pointer to an alternative expression of the whole "location", not particularly the geometry of the location. To use it for that requires a lot of implied semantics - follow the URI, find the property/properties in the returned data object that could represent a geometry, and then use those.
