### ISSUE TITLE
Controlled vocabulary / Codelist on regional, municipality or even Street level needed

### ISSUE THREAD

**Issue by frank-steimke** [SEMICeu/Core-Location-Vocabulary#6]
In Germany and other MS specific keys and codes do exist on regional and municipality level. A concept going a level deeper than adminUnitL1 (country) and adminUnitL2 (county) might be needed.

The current Core Location “Address” component only has code data type in adminUnitL1 only and adminUnitL2 as literal.

In order to express national code values as URIs / Codes in address components an additional field adminUnitL2 (or adminUnitL3) data type “URI” should be added. Another option would be an optional, repeatable field AddressCode, so that we can - in our use case - assign the Code for the Street as well as coding of the municipality.

Exemplary values of a German municipality key called “Allgemeiner Gemeindeschlüssel” (AGS) that could be used in a core location address element can be found here in the German DCAT-AP.de. DCAT-AP.de extends Core Location at several points and adds own national URIs for Geocoding https://www.dcat-ap.de/def/politicalGeocoding/municipalityKey/  

Other Member States have URI-encoded geopolitical encodings too and there is the EU nuts code that does not fit properly in the adminUnitL2 as "Text".

**Comment by dimi-schepers** [comment]
Thank you for the information. During the Core Vocs webinar dd. 2021-05-20, an agreement was reached to use Code as datatype for all the AdminUnitLevels. We propose to continue the discussion on the various levels and which codelist to use per level in issue #12.
