### ISSUE TITLE
General comment : modelling approach

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Location-Vocabulary#7]
I think Core Location Vocabulary now has a more limited usage wrt to what was possible in the past. In the past address and geometry were two properties very general to be attached to owl:Thing (or better rdfs:Resource). Currently, in order to specify an address you have to pass through a location? Why? 
I think an analogous discussion was done in the context of the SDGSandbox work.

BTW: AdminLevel1 and AdminLevel2 are already named places being components of the address (according to INSPIRE data model). Therefore, it is difficult to understand why modelling in such a way, unless with named place i.e., Location you mean something very broad like also a Site of an Organisation, a parking, a bus stop, or anything  with a geographical dimension.

I think this part should be really clarified.

**Comment by dimi-schepers** [comment]
Thanks for highlighting this. To clarify, it is not our intention to limit the usage of the address and geometry properties. We reused the structure of the visual [as it existed in version 1](https://github.com/SEMICeu/Core-Location-Vocabulary/blob/master/releases/1.00/Core_Vocabularies-Business_Location_Person_v1.00_Conceptual_Model.png). However, as we didn't produce the Turtle-file yet, it is now indeed impossible to see the domains of the properties. A better visual would therefore be the following.

![Core_Location](https://user-images.githubusercontent.com/45657147/118788367-04322d80-b894-11eb-9ecf-cfcbd90fd821.jpg)

**Comment by giorgialodi** [comment]
yep now it is clearer and definitely more flexible so that we can use the properties also in other Core Vocabularies. Thanks @dimi-schepers!
