### ISSUE TITLE
Geometry of an address

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/Core-Location-Vocabulary#9]
In the past version of CLV (I am referring to this one https://www.w3.org/ns/locn) it was possible to specify a geometry for an address. Indeed an address may have a geometry.

How can I do that now? A location, i.e., "named place", has a geometry. Is an address a location? (probably yes BTW).

**Comment by dimi-schepers** [comment]
Please see the comment made in issue https://github.com/SEMICeu/Core-Location-Vocabulary/issues/7#issuecomment-843915663
